name: Publish to npm registry

on:
  workflow_dispatch:
    inputs:
      version:
        description: "version | patch | minor | major"
        required: true
        default: "patch"
jobs:
  publish:
    environment: release 
    runs-on: ubuntu-latest
    name: 'Bump version and publish'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/heads/master
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci 
      - name: version and publish
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email gh-actions-${GITHUB_ACTOR}@github.com
          git remote add gh-origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          npm version $VERSION -m "Version %s"
          npm publish
          git push gh-origin master --tags
        env:
          CI: true
          VERSION: ${{ github.event.inputs.version }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
